[project]
name = "aks-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "uvicorn>=0.27.1",
    "starlette>=0.36.3",
    "click>=8.1.8",
]
